version: '3'

services:
  api:
    volumes:
      - ./src/node_api_test:/app
    entrypoint:
      - "npm"
      - "start"
  frontend_app:
    volumes:
      - ./src/node_simple_static_server:/app
    entrypoint:
      - "npm"
      - "start"
