version: '3'

services:
  db:
    image: mongo:4.0.3
    volumes:
      - data:/data/db
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - 3000:$PORT
    environment:
      PORT: $PORT
      MONGO: $MONGO
    depends_on:
      - db

volumes:
  data:
