version: '3'

services:
  db:
    image: mongo:4.0.3
    volumes:
      - data:/data/db
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - 3000:$API_PORT
    environment:
      PORT: $API_PORT
      MONGO: $MONGO
      IMGUR_URL: $IMGUR_URL
      IMGUR_CLIENT_ID: $IMGUR_CLIENT_ID
    depends_on:
      - db
  frontend_app:
    build:
      context: .
      dockerfile: front.Dockerfile
    ports:
      - 8000:$FRONT_PORT
    environment:
      PORT: $FRONT_PORT
      API_URL: $API_URL

volumes:
  data:
