version: '3'

services:
  db:
    image: mongo
    volumes:
      - data:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  data:
